# Generated by Django 3.1 on 2020-08-19 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('held_on', models.DateField(auto_now_add=True)),
                ('is_played', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('club_state', models.CharField(default='', max_length=200)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs', models.IntegerField(default=0)),
                ('fifty', models.CharField(choices=[('0', '0'), ('1', '1')], default='0', max_length=2)),
                ('hundreds', models.CharField(choices=[('0', '0'), ('1', '1')], default='n', max_length=2)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_p_h', to='teams.team')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_h', to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('jersey_number', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamcountry', to='teams.countries')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamplayers', to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='MatchPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_p', to='teams.matches')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_p', to='teams.team')),
            ],
        ),
        migrations.AddField(
            model_name='matches',
            name='team_a_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_a', to='teams.team'),
        ),
        migrations.AddField(
            model_name='matches',
            name='team_b_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_b', to='teams.team'),
        ),
        migrations.AddField(
            model_name='matches',
            name='winner',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
    ]
